# Generated by Django 5.0.14 on 2025-09-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Admin')], default=0),
        ),
    ]
