# Generated by Django 5.0.14 on 2025-09-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
