# Generated by Django 5.0.14 on 2025-09-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password_hashed',
        ),
    ]
