# Generated by Django 5.0.14 on 2025-09-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_brand_logo_url_brand_image_alter_gender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isOnSale',
        ),
    ]
