# Generated by Django 5.0.14 on 2025-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gender_name_remove_product_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='genders',
            field=models.ManyToManyField(to='core.gender'),
        ),
    ]
