# Generated by Django 5.0.14 on 2025-09-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_gender_product_genders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genders',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.gender'),
        ),
    ]
