# Generated by Django 5.0.14 on 2025-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_city_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
