# Generated by Django 5.0.14 on 2025-09-21 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotconversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='chatbotconversation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='faq_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faq'),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='source',
            field=models.CharField(choices=[('faq', 'FAQ'), ('ai', 'AI'), ('manual', 'Manual')], default='ai', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
