# Generated by Django 5.0.14 on 2025-09-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_faqcategory_alter_faq_updated_at_faq_category_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unansweredquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatBotConversation',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='UnansweredQuestion',
        ),
    ]
