# Generated by Django 5.0.14 on 2025-09-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_chatsession_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
