# Generated by Django 5.0.14 on 2025-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_faq_delete_faqcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
