# Generated by Django 5.0.14 on 2025-09-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_product_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_discount_percentage',
        ),
    ]
