# Generated by Django 5.0.14 on 2025-10-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_review_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
