# Generated by Django 5.0.14 on 2025-10-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
