# Generated by Django 5.0.14 on 2025-10-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_confirmed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_confirmed', 'Đơn hàng được xác nhận'), ('order_shipped', 'Đơn hàng đã giao hàng'), ('order_delivered', 'Đơn hàng đã giao thành công'), ('order_cancelled', 'Đơn hàng bị hủy'), ('promotion', 'Khuyến mãi mới'), ('system', 'Thông báo hệ thống')], max_length=20),
        ),
    ]
