# Generated by Django 5.0.14 on 2025-11-14 13:13

import django.db.models.deletion
from django.db import migrations, models, connection


def remove_fields_if_exists(apps, schema_editor):
    """Remove old fields from ChatbotFeedback if they exist"""
    db_table = 'core_chatbotfeedback'
    with connection.cursor() as cursor:
        # Get existing columns
        cursor.execute(f"SHOW COLUMNS FROM `{db_table}`")
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Remove columns if they exist
        columns_to_remove = ['conversation_id', 'feedback_text', 'rating']
        for column in columns_to_remove:
            if column in existing_columns:
                try:
                    cursor.execute(f"ALTER TABLE `{db_table}` DROP COLUMN `{column}`")
                except Exception:
                    pass  # Ignore errors if column doesn't exist


def add_fields_if_not_exists(apps, schema_editor):
    """Add new fields to ChatbotFeedback if they don't exist"""
    db_table = 'core_chatbotfeedback'
    with connection.cursor() as cursor:
        # Get existing columns
        cursor.execute(f"SHOW COLUMNS FROM `{db_table}`")
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Add columns if they don't exist
        if 'feedback_type' not in existing_columns:
            cursor.execute(f"ALTER TABLE `{db_table}` ADD COLUMN `feedback_type` varchar(20) NOT NULL DEFAULT 'positive'")
        if 'intent' not in existing_columns:
            cursor.execute(f"ALTER TABLE `{db_table}` ADD COLUMN `intent` varchar(50) NOT NULL DEFAULT ''")
        if 'message' not in existing_columns:
            cursor.execute(f"ALTER TABLE `{db_table}` ADD COLUMN `message` longtext NOT NULL")
        if 'response' not in existing_columns:
            cursor.execute(f"ALTER TABLE `{db_table}` ADD COLUMN `response` longtext NOT NULL")
        if 'session_id' not in existing_columns:
            cursor.execute(f"ALTER TABLE `{db_table}` ADD COLUMN `session_id` varchar(100) NULL")
        if 'user_id' not in existing_columns:
            cursor.execute(f"ALTER TABLE `{db_table}` ADD COLUMN `user_id` varchar(100) NULL")


def reverse_remove_fields(apps, schema_editor):
    """Reverse migration - do nothing"""
    pass


def create_tables_if_not_exists(apps, schema_editor):
    """Create tables only if they don't exist"""
    db_table_prefix = 'core_'
    tables_to_create = ['alert', 'botconfig', 'intenttraining', 'conversationtag']
    
    with connection.cursor() as cursor:
        # Get existing tables
        cursor.execute("SHOW TABLES")
        existing_tables = [row[0] for row in cursor.fetchall()]
        
        # Create tables if they don't exist (using RunPython to create models)
        # This is handled by Django's CreateModel, but we need to check first
        pass  # Django will handle this, we just need to catch the error


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_chatbotmetrics'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS `core_alert` ("
            "`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, "
            "`alert_type` varchar(50) NOT NULL, "
            "`title` varchar(200) NOT NULL, "
            "`message` longtext NOT NULL, "
            "`severity` varchar(20) NOT NULL, "
            "`is_resolved` bool NOT NULL, "
            "`resolved_at` datetime(6) NULL, "
            "`created_at` datetime(6) NOT NULL"
            ")",
            reverse_sql="DROP TABLE IF EXISTS `core_alert`",
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS `core_botconfig` ("
            "`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, "
            "`key` varchar(100) NOT NULL UNIQUE, "
            "`value` json NOT NULL, "
            "`description` longtext NOT NULL, "
            "`updated_at` datetime(6) NOT NULL"
            ")",
            reverse_sql="DROP TABLE IF EXISTS `core_botconfig`",
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS `core_intenttraining` ("
            "`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, "
            "`intent_name` varchar(50) NOT NULL UNIQUE, "
            "`description` longtext NOT NULL, "
            "`keywords` json NOT NULL, "
            "`phrases` json NOT NULL, "
            "`response_template` longtext NOT NULL, "
            "`is_active` bool NOT NULL, "
            "`created_at` datetime(6) NOT NULL, "
            "`updated_at` datetime(6) NOT NULL"
            ")",
            reverse_sql="DROP TABLE IF EXISTS `core_intenttraining`",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Alert',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('alert_type', models.CharField(choices=[('high_fallback', 'High Fallback Rate'), ('api_error', 'API Error'), ('db_error', 'Database Error'), ('low_confidence', 'Low Confidence Score'), ('slow_response', 'Slow Response Time'), ('system', 'System Alert')], max_length=50)),
                        ('title', models.CharField(max_length=200)),
                        ('message', models.TextField()),
                        ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                        ('is_resolved', models.BooleanField(default=False)),
                        ('resolved_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='BotConfig',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('key', models.CharField(max_length=100, unique=True)),
                        ('value', models.JSONField()),
                        ('description', models.TextField(blank=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Bot Configuration',
                        'verbose_name_plural': 'Bot Configurations',
                        'ordering': ['key'],
                    },
                ),
                migrations.CreateModel(
                    name='IntentTraining',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('intent_name', models.CharField(max_length=50, unique=True)),
                        ('description', models.TextField(blank=True)),
                        ('keywords', models.JSONField(default=list)),
                        ('phrases', models.JSONField(default=list)),
                        ('response_template', models.TextField(blank=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Intent Training',
                        'verbose_name_plural': 'Intent Training Data',
                        'ordering': ['intent_name'],
                    },
                ),
            ],
        ),
        # Remove old fields only if they exist
        migrations.RunPython(
            remove_fields_if_exists,
            reverse_remove_fields,
        ),
        # Update state to reflect removed fields (for Django's state tracking)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='chatbotfeedback',
                    name='conversation',
                ),
                migrations.RemoveField(
                    model_name='chatbotfeedback',
                    name='feedback_text',
                ),
                migrations.RemoveField(
                    model_name='chatbotfeedback',
                    name='rating',
                ),
                migrations.RemoveField(
                    model_name='chatbotfeedback',
                    name='user',
                ),
            ],
        ),
        # Add new fields only if they don't exist
        migrations.RunPython(
            add_fields_if_not_exists,
            reverse_remove_fields,
        ),
        # Update state to reflect added fields
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='chatbotfeedback',
                    name='feedback_type',
                    field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=20),
                ),
                migrations.AddField(
                    model_name='chatbotfeedback',
                    name='intent',
                    field=models.CharField(blank=True, max_length=50),
                ),
                migrations.AddField(
                    model_name='chatbotfeedback',
                    name='message',
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name='chatbotfeedback',
                    name='response',
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name='chatbotfeedback',
                    name='session_id',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='chatbotfeedback',
                    name='user_id',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS `core_conversationtag` ("
            "`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, "
            "`tag_name` varchar(50) NOT NULL, "
            "`note` longtext NOT NULL, "
            "`created_at` datetime(6) NOT NULL, "
            "`conversation_id` bigint NOT NULL, "
            "UNIQUE (`conversation_id`, `tag_name`), "
            "FOREIGN KEY (`conversation_id`) REFERENCES `core_chatbotconversation` (`id`)"
            ")",
            reverse_sql="DROP TABLE IF EXISTS `core_conversationtag`",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.chatbotconversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('conversation', 'tag_name')},
            },
        ),
            ],
        ),
    ]
